### ISSUE TITLE
Basic roadmap

### ISSUE THREAD

**Issue by RobotoSkunk** [ClockBomb-Games/PixelMan-Adventures#1]
# TODO

> This is just a TODO List containing all things that are needed to make the first version of PixelMan work as intended.

## *(2023-09-18)*

- [x] Add the game objects physics system.
- [x] Add the player.
    - [x] Add a second player.
    - [x] Add the camera following the player.
        - [x] Make the camera follow the player in single mode levels.
        - [x] Split the screen and follow the players in multiplayer mode levels.
        - [x] Smooth camera movement.
        - [x] Move the camera slightly to the left or the right when the player moves.
        - [x] Slightly zoom out depending on the player's velocity.
- [x] Make the player interact with springs.
    - [x] In any direction.
- [x] Make the player interact with moving platforms.
    - [x] Horizontally.
    - [x] Vertically.
- [x] Make the player interact with killzones.
    - [x] Add the game over effect.
    - [x] Make the entire level reset.
- [x] Add the swivel gun.
- [x] Add the rocket launcher.
- [x] Add the ability to pause the game and resume.
- [x] Add the gravity switcher.
- [x] Add saws.
- [x] Add saws base.
- [x] Add moving saws.
- [x] Add mobile saws (saws that are in a mini car).
    - [x] Make the mobile saws interact with the above stuff.
